== Dynamic Bug Overlay Component
This component allows you to overlay a static image (or bug) onto a video stream. It provides a customizable interface for configuring the bug's position and includes runtime controls for dynamic adjustments.

It offers the ability to update or remove the overlay image during runtime, making it highly adaptable for various broadcasting and video processing needs.

=== Configuration

[cols="2,6,^1",options="header"]
|===
|Option | Description | Required
| id | A unique identifier for the component instance | ✓
| displayName | The name shown in the Studio UI of this component | ✓
| initialBug | The initial bug to render on the video, if any | 𐄂
| initialPosition a| The initial position for the bug overlay on the video.  One of:

- topleft
- topright
- bottomleft
- bottomright | 𐄂
|===

=== Runtime Control (UI)

The component provides a UI for runtime control, allowing users to interact with the overlay in real time. This allows you to:

* View the current configuration.
* Adjust the bug's position and image through a form.
* Upload new bugs / images

=== Runtime Control API

The DynamicBug component also exposes an HTTP JSON API for runtime control, enabling programmatic interaction.

As with all Studio Runtime Control APIs, the base URL of the API is `http://127.0.0.1:8000/live/api/{componentId}`
where `{componentId}` is the id of the component you are controlling.  So for example if you have a DynamicBug with id `dynamicBug` the base URL would be `http://127.0.0.1:8000/live/api/bynamicBug/`.

[cols="1,1,2,3",options="header"]
|===
| URL | Method | Description | Response

| active-bug | GET | Retrieves the current bug (if any) and its position |
| bugs | GET | Retrieves a list of available bug images |
|===

[cols="1,1,2,3",options="header"]
|===
| URL | Method | Description | Payload
| active-bug | DELETE | Removes the current bug overlay |
| active-bug | POST | Updates the bug overlay with a new image or position
a|
[source, json]
----
{
  "bug": The name of the bug to overlay,
  "position": The position to display the bug (one of `topLeft`, `topRight`...)
}
----
| active-bug | POST | A post with an empty JSON payload `{}` deletes removes the current bug. | `{}`
|===



For example, you can send a POST request to update the position of the bug controlled by a DynmaicBup component with `id` of `dynamicBug` as follows:

[source, bash]
----
curl -H "Accept: application/json" -H "Content-type: application/json" -X POST -d '{"bug": "trinorsk.png", "position": "topright"}' http://127.0.0.1:8000/live/api/dynamicBug/active-bug
----

The above request now moves the bug from the default topleft corner to topright - you can experiment with it by moving the bug to different positions.



== Example

OverlayBug screenshot - form and running with topleft and bottom right
SHow a new image upload


=== Environment Overrides

[cols="1,2,1",options="header"]
|===
| NAME | Description | Default Value
| DYNAMICBUG_DIRECTORY | The subdirectory from which all DynamicBug components read image files and to which new images are uploaded | bugs
|===

=== YAML Override Example
TBD

[source, yaml]
----
- type: processor.dynamicBug
    config:
      displayName: dynamicBug
      initialBug: trinorsk.png
      initialPosition: topleft
      id: dynamicbug
    subscriptions:
      - source: srt-listener
        streams:
          type: take-specific-stream
          select:
            - video
          filter: camera1
----


