version : “3”
services:
  nginx:
    image: nginx:latest
    container_name: nginx_container
    extra_hosts:
    - "host.docker.internal:host-gateway"
    ports:
      # re-direct to 443
      - 80:80

      # studio
      - 443:443

      # norsk
      - 8443:8443
    volumes:
      - ${NGINX:-./support/nginx.conf}:/etc/nginx/nginx.conf
      - ./support/key.pem:/root/ssl/key.pem
      - ./support/cert.pem:/root/ssl/cert.pem
