openapi: 3.0.0
info:
  title: RTMP Input Component
  version: 1.0.0

paths:
  /disconnect:
    post:
      summary: Disconnect an RTMP stream
      description: Disconnects an active RTMP stream by stream name
      x-route-type: instance
      requestBody:
        description: The stream to disconnect
        content:
          application/json:
            schema:
              type: object
              required: ['streamName']
              properties:
                streamName:
                  type: string
                  description: The name of the stream to disconnect
                  example: camera1
      responses:
        204:
          description: The stream was successfully disconnected
        404:
          description: The specified stream was not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: A description of the error
                  details:
                    type: string
                    description: Additional error details
        500:
          description: Failed to disconnect the stream
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: A description of the error
                  details:
                    type: string
                    description: Additional error details

  /enable:
    post:
      summary: Re-enables a disabled RTMP stream
      description: Re-enables a previously disconnected RTMP stream
      x-route-type: instance
      requestBody:
        description: The stream to re-enable
        content:
          application/json:
            schema:
              type: object
              required: ['streamName']
              properties:
                streamName:
                  type: string
                  description: The name of the stream to re-enable
                  example: camera1
      responses:
        204:
          description: The stream was successfully re-enabled
        400:
          description: Stream is already connected or invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: A description of the error
                  details:
                    type: string
                    description: Additional error details
        500:
          description: Failed to re-enable stream
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: A description of the error
                  details:
                    type: string
                    description: Additional error details
  
  /disable:
    post:
      summary: Disables an RTMP stream by id
      description: 
      x-route-type: instance
      requestBody:
        description: The stream to disable
        content:
          application/json:
            schema:
              type: object
              required: ['streamId']
              properties:
                streamId:
                  type: string
                  description: The Id of the stream to disable
                  example: camera1
      responses:
        204:
          description: The stream was successfully disabled
        400:
          description: The stream isn't known about, or invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: A description of the error
                  details:
                    type: string
                    description: Additional error details
        500:
          description: Failed to disable stream
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: A description of the error
                  details:
                    type: string
                    description: Additional error details

