openapi: 3.0.0
info:
  title: LinkedIn Output Component
  version: 1.0.0
components:
  schemas:
    linkedInOutputSettings:
      type: object
      properties:
        id:
          type: string
        displayName:
          type: string
        streamUrl:
          type: string
        notes: 
          type: string
      required: ['id', 'displayName','streamUrl']

