== Stream Key Override
Override stream keys for several streams at once, setting some components of the keys and optionally incrementing stream ID.

This is useful for renaming streams before they go to outputs, or for gathering multiple streams together for processors and outputs that expect a single stream or a single program, like `output.autoCmaf`.

=== Component Configuration
[cols="2,6,^1",options="header"]
|===
| Option | Description | Required
| id | A unique identifier for the component instance | âœ“
| displayName | The name shown in the Studio UI of this component | âœ“
| mode | Multi-stream behavior (default: &quot;simple&quot;) |  ğ„‚
| output | Output individual streams or a single merged stream (default: &quot;individually-selectable&quot;) |  ğ„‚
| sourceName | Override source name |  ğ„‚
| programNumber | Override program number |  ğ„‚
| streamId | Override stream ID |  ğ„‚
| renditionName | Override rendition name |  ğ„‚
|===


=== Modes

Each mode overrides the stream key of streams individually.

==== 'simple'

For each stream key component specified in config, it will override that component of the existing stream key directly.

If all components of the stream key are specified in config, it can only accept one stream, because stream keys need to be unique.

==== 'by-media-type'

This overrides stream keys in a similar manner, but increments the Stream ID according to the media type, to help ensure that video, audio, subtitles, etc. remain distinct while still remaining predictable.

==== 'in-order'

This also increments Stream IDs, not according to media type, but according to the order that they arrive.
This mode is non-deterministic and the assigned Stream IDs may change between runs.
On the other hand, it ensures that all streams have unique stream keys.
