openapi: 3.0.0
info:
  title: Onscreen Graphics Overlay Component
  version: 1.0.0

paths:
  # Static paths (available at runtime and design time)
  /graphics:
    get:
      summary: Return the currently available graphic files
      description: Returns all the graphics files on the server
      x-route-type: static
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                description: A list of the graphic files available
                items:
                  $ref: "#/components/schemas/graphic"
    post:
      summary: Upload a new graphic
      description: Upload a new graphic as a multi-part form POST
      x-route-type: static
      requestBody:
          description: A multipart form containing the file to upload)
          content:
            multipart/form-data:
              schema:
                type: object
                properties:
                  # The property name 'file' will be used for all files.
                  file:
                    type: string
                    format: binary
                    required: [file]
      responses:
        204:
          description: The file was uploaded successfully
        400:
          description: No file was uploaded
        404:
          description: Not Found
        409:
          description: A graphic with the same name already exists
        500:
          description: File upload failed
  /graphic:
    delete:
      summary: Delete a graphic file from the server
      description: Deletes the passed filename from the server if present
      x-route-type: static
      tags: [foo]
      requestBody:
        description: The graphic to delete
        content:
            application/json:
              schema:
                type: object
                properties:
                  filename:
                    type: string
                    description: 'The name of the graphic file to delete'
                    example: graphic.png
                required: ['filename']
      responses:
        204:
          description: The graphic was successfully deleted
        404:
          description: The specified graphic was not found
        500:
          description: Failed to delete the graphic

  # Component instance paths (available at runtime only)
  /active-graphic:
    get:
      summary: Info about the current graphic
      description: Returns the configuration for current the onscreen graphic is any
      x-route-type: instance
      responses:
        200:
          description: Details of the configured graphic
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/config"
        204:
          description: No graphic configured
        404:
          description: Component not found
    post:
      summary: Change the current graphic file and/or position
      description: Change the current graphic file and/or position
      x-route-type: instance
      requestBody:
          description: The graphic filename and location (sending an empty JSON object will delete the graphic)
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/config"
                  - $ref: "#/components/schemas/emptyObject"
      responses:
        204:
          description: The active graphic was successfully updated
        400:
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        404:
          description: Component not found
    delete:
      summary: Stop displaying the current graphic
      x-route-type: instance
      responses:
        204:
          description: The active graphic was successfully hidden
        404:
          description: Component not found

components:
  schemas:
    position:
      type: object
      properties:
        x:
          type: number
          description: X coordinate position
          minimum: 0
          maximum: 1920
        y:
          type: number
          description: Y coordinate position
          minimum: 0
          maximum: 1080
      required:
        - x
        - y
    graphic:
      type: string
      description: The name of the image file
      example: Norsk.png
    config:
      type: object
      description: The configuration for the onscreen graphic
      properties:
        graphic:
          $ref: "#/components/schemas/graphic"
        position:
          $ref: "#/components/schemas/position"
    emptyObject:
      type: object
      example: {}
    errorResponse:
      type: object
      description: Details of why the request failed
      properties:
        error:
          type: string
          description: A description of the error
        details:
          type: string
          description: The unacceptable data


# components:
#   schemas:
#     position:
#       type: string
#       description: Where the graphic is to be displayed
#       example: "topright"
#       enum:
#         - topleft
#         - topright
#         - bottomleft
#         - bottomright
#     graphic:
#       type: string
#       description: The name of the image file
#       example: Norsk.png
#     config:
#       type: object
#       description: The configuration for the onscreen graphic
#       properties:
#         graphic:
#           $ref: "#/components/schemas/graphic"
#         position:
#           $ref: "#/components/schemas/position"
#     emptyObject:
#       type: object
#       example: {}
#     errorResponse:
#       type: object
#       description: Details of why the request failed
#       properties:
#         error:
#           type: string
#           description: A description of the error
#         details:
#           type: string
#           description: The unacceptable data

