/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Where the graphic is to be displayed
         * @example topright
         * @enum {string}
         */
        position: "topleft" | "topright" | "bottomleft" | "bottomright";
        /**
         * @description The name of the image file
         * @example Norsk.png
         */
        graphic: string;
        /** @description The configuration for the onscreen graphic */
        config: {
            graphic?: components["schemas"]["graphic"];
            position?: components["schemas"]["position"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
