openapi: 3.0.0
components:
  schemas:
    position:
      type: string
      description: "Where the graphic is to be displayed"
      example: 'topright'
      enum:
        - topleft
        - topright
        - bottomleft
        - bottomright
    graphic:
      type: string
      description: "The name of the image file"
      example: 'Norsk.png'
    config:
      type: object
      description: "The configuration for the onscreen graphic"
      properties:
        graphic:
          $ref: "#/components/schemas/graphic"
        position:
          $ref: "#/components/schemas/position"

