openapi: 3.0.0
info:
  title: Youtube Output Component
  version: 1.0.0
components:
  schemas:
    youtubeOutputSettings:
      type: object
      properties:
        id:
          type: string
        displayName:
          type: string
        streamKey:
          type: string
        notes: 
          type: string
      required: ['id', 'displayName', 'streamKey']

