name: Run Tests

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:


jobs:
  run-tests:
    runs-on: ubuntu-latest
    # runs-on: self-hosted

    steps:
    - name: Checkout the head commit of the branch
      uses: actions/checkout@v2

    - name: Write license file
      id: create-json
      uses: jsdaniell/create-json@v1.2.3
      with:
        name: "norsk_license.json"
        json: ${{ secrets.NORSK_LICENSE }}

    # this would just be a service but you can't override the entry point, dull..
    - name: Run Norsk 
      uses: gacts/run-and-post-run@v1
      with:
        run: "docker run  --name norsk -d --mount type=bind,source=${{github.workspace}},target=${{github.workspace}} --mount type=bind,source=${{github.workspace}}/norsk_license.json,target=/mnt/license.json,readonly --net=host norskvideo/norsk --license-file /mnt/license.json"
        post: docker stop norsk 

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v4
    - name: Run the Magic Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@v2

    - name: Nix env
      uses: rrbutani/use-nix-shell-action@v1
      with:
        file: shell.nix

    - name: Run Build (With Latest)
      run: "npm install --workspaces @norskvideo/norsk-sdk@latest && npm install @norskvideo/norsk-studio@latest && npm install && npm run build"

    - name: Run Tests 
      run: "./scripts/gh-tests.sh"
      timeout-minutes: 20

    - name: Discord Webhook Action
      uses: tsickert/discord-webhook@v5.3.0
      if: always()
      with:
        webhook-url: ${{ secrets.DISCORD_URL }}
        raw-data: discord.json

    - name: Dump norsk logs
      if: failure()
      uses: jwalton/gh-docker-logs@v2
      with:
        images: 'norsk'
        dest: './logs'

    - name: Tar logs
      if: failure()
      run: tar cvzf ./logs.tgz ./logs

    - name: Upload VD report to GitHub
      if: failure()
      uses: actions/upload-artifact@master
      with:
        name: vd.json
        path: ./vd.json

    - name: Upload Built-in report to GitHub
      if: failure()
      uses: actions/upload-artifact@master
      with:
        name: built-ins.json
        path: ./built-ins.json

    - name: Upload docker logs to GitHub
      if: failure()
      uses: actions/upload-artifact@master
      with:
        name: logs.tgz
        path: ./logs.tgz
