name: Run Tests

on:
  workflow_call:
    inputs:
      notify_discord:
        required: false
        default: false
        type: boolean
      run_context:
        required: false
        default: "No context"
        type: string

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the head commit of the branch
      uses: actions/checkout@v2

    - name: Write license file
      id: create-json
      uses: jsdaniell/create-json@v1.2.3
      with:
        name: "norsk_license.json"
        json: ${{ secrets.NORSK_LICENSE }}

    - name: Run Norsk 
      uses: gacts/run-and-post-run@v1
      with:
        run: "docker run --pull=always --rm --name norsk -d --mount type=bind,source=${{github.workspace}}/norsk_license.json,target=/mnt/license.json,readonly -p 6791:6791 -p 6790:6790 -p 8080:8080 norskvideo/norsk --license-file /mnt/license.json"
        post: docker stop norsk 

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v4
    - name: Run the Magic Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@v2

    - name: Nix env
      uses: rrbutani/use-nix-shell-action@v1
      with:
        file: shell.nix

    - name: Run Build (With Latest)
      run: "npm install --workspaces @norskvideo/norsk-sdk@latest && npm install @norskvideo/norsk-studio@latest && npm install && npm run build"

    - name: Run Tests
      env: 
        RUNNER: ${{ runner.name }}
        CONTEXT: ${{ inputs.run_context }}
        GITHUB_REF: ${{ github.ref }}
        GITHUB_RUN_ID: ${{ github.run_id }}
      run: "./scripts/gh-tests.sh"
      timeout-minutes: 20

    - name: Discord Webhook Action
      uses: tsickert/discord-webhook@v5.3.0
      if: ${{ always() && inputs.notify_discord && hashFiles('discord.json') != '' }} 
      with:
        webhook-url: ${{ secrets.DISCORD_URL }}
        raw-data: discord.json

    - name: Discord Webhook Action
      uses: tsickert/discord-webhook@v5.3.0
      if: ${{ failure() && inputs.notify_discord && hashFiles('discord.json') == '' }} 
      with:
        webhook-url: ${{ secrets.DISCORD_URL }}
        username: "Evil Jenkins"
        avatar-url: "https://i.imgur.com/HzrYPqf.png"
        content: ""
        embed-title: "Norsk Studio Defaults Tests Failed"
        embed-color: 15548997
        embed-description: | 
          No Results File Found 
          ${{inputs.run_context}}

    - name: Dump norsk logs
      if: always()
      uses: jwalton/gh-docker-logs@v2
      with:
        images: 'norsk'
        dest: './logs'

    - name: Tar logs
      if: always()
      run: tar cvzf ./logs.tgz ./logs

    - name: Upload VD report to GitHub
      if: always()
      uses: actions/upload-artifact@master
      with:
        name: vd.json
        path: ./vd.json

    - name: Upload Built-in report to GitHub
      if: always()
      uses: actions/upload-artifact@master
      with:
        name: built-ins.json
        path: ./built-ins.json

    - name: Upload Built-in logs to GitHub
      if: always()
      uses: actions/upload-artifact@master
      with:
        name: built-ins.log
        path: workspaces/built-ins/logs/debug.log

    - name: Upload VD logs to GitHub
      if: always()
      uses: actions/upload-artifact@master
      with:
        name: vd.log
        path: workspaces/vision-director/logs/debug.log

    - name: Upload docker logs to GitHub
      if: always()
      uses: actions/upload-artifact@master
      with:
        name: logs.tgz
        path: ./logs.tgz
