name: Update deps

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:


jobs:
  auto-update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the head commit of the branch
      uses: actions/checkout@v2

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v4
    - name: Run the Magic Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@v2

    - name: Nix env
      uses: rrbutani/use-nix-shell-action@v1
      with:
        file: shell.nix

    - name: Run auto dependency update 
      uses: romoh/dependencies-autoupdate@v1.2
      with: 
        token: ${{secrets.GITHUB_TOKEN}}
        update-command: "'npm install --workspaces @norskvideo/norsk-sdk@latest && npm install --workspaces @norskvideo/norsk-studio@latest && npm install && npm run build'"
